from typing import Protocol

from aro.domain.alerting.entities import Alert
from aro.domain.shared.value_objects import AlertId, Criticity


class AlertRepository(Protocol):
    def add(self, alert: Alert) -> None: ...
    def get_by_id(self, alert_id: AlertId) -> Alert | None: ...
    def list_open(self, limit: int, criticity: Criticity | None) -> list[Alert]: ...
    def update(self, alert: Alert) -> None: ...


class AlertExplainer(Protocol):
    def explain(self, alert: Alert) -> str: ...
